### ISSUE TITLE
Installation via npm

### ISSUE THREAD

**Issue by machawk1** [amitmerchant1990/pomolectron#3]
Per the README, I execute `npm install pomolectron` but need further instruction on how to run the application. There are no further instructions for running the application for the installation method under "How to Use". 

After installing:
```sh
$ pomolectron
-bash: pomolectron: command not found
```

Please advise.

**Comment by amitmerchant1990** [comment]
@machawk1 You need to further do the following things and you're good to go:

```bash
$> cd PATH-TO-POMOLECTRON
$> npm install && npm start
```

Thanks!

**Comment by machawk1** [comment]
@amitmerchant1990 Per the README, I am installing through `npm`, not from source.

After running `npm install pomolectron`, what is the path to `PATH-TO-POMOLECTRON`?

`which pomolectron` returns nothing.

**Comment by amitmerchant1990** [comment]
`PATH-TO-POMOLECTRON` is the directory of the app.

**Comment by machawk1** [comment]
When installing via npm, how does one acquire the directory of the app?

**Comment by stephenwithav** [comment]
`~/node_modules/pomolectron`

**Comment by machawk1** [comment]
Thanks, @stephenwithav . Perhaps this information should reside in the README instructions for installing and running Pomolectron.

**Comment by stephenwithav** [comment]
Done, @machawk1.

**Comment by lmj0011** [comment]
## If you just want to open this app by entering `pomolectron` in Bash

after installing...

add this to your `.bashrc`
alias promolectron='(cd /home/YOUR_USERNAME/node_modules/pomolectron/ && npm start)'

then run ` source ~/.bashrc`

now you can call the command with `pomolectron`
