### ISSUE TITLE
WTF is that icon dude?

### ISSUE THREAD

**Issue by vko-online** [amitmerchant1990/pomolectron#8]
<img width="697" alt="screen shot 2017-07-04 at 13 20 26" src="https://user-images.githubusercontent.com/4560099/27819348-9786ca12-60bb-11e7-95d6-664537ae5889.png">

I dont like pomodoro from appstore, so gave it a try, sorry but UI and icons are awful

**Comment by amitmerchant1990** [comment]
@vko-online Sorry that the icon and the overall UI disappointed you. As I don't have any machine with macOS, I can't test it properly on same.

If you feel so that the design is awful then you can contribute and make it a better Pomodoro app. Suggestions are always welcome.
